repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: end-of-file-fixer
        files: ^services/
      - id: trailing-whitespace
        files: ^services/
      - id: mixed-line-ending
        args: [--fix=lf]
        files: ^services/
      - id: check-yaml
        files: ^services/.*\.(yaml|yml)$
      - id: check-json
        files: ^services/.*\.json$
      - id: check-toml
        files: ^services/.*\.toml$
      - id: debug-statements
        files: ^services/.*\.py$

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.0
    hooks:
      - id: ruff
        args: [--fix]
        files: ^services/.*\.py$
      - id: ruff-format
        files: ^services/.*\.py$
