import {
  SESSION_COUNTDOWN_DURATION_MINUTES,
  SESSION_COUNTDOWN_PULSE_LAST_SECONDS,
  SESSION_COUNTDOWN_RED_BELOW_MINUTES,
} from '@/constants/sessionCountdown'

const MS_PER_MINUTE = 60_000
const MS_PER_SECOND = 1_000

export const SESSION_COUNTDOWN_DURATION_MS = SESSION_COUNTDOWN_DURATION_MINUTES * MS_PER_MINUTE
export const SESSION_COUNTDOWN_RED_BELOW_MS = SESSION_COUNTDOWN_RED_BELOW_MINUTES * MS_PER_MINUTE
export const SESSION_COUNTDOWN_PULSE_AT_OR_BELOW_MS =
  SESSION_COUNTDOWN_PULSE_LAST_SECONDS * MS_PER_SECOND
