INSERT INTO public."permission" (permission_key,description) VALUES
	 ('ACCESS WEB APP','PERMISSION TO ACCESS WEB APP'),
	 ('ACCESS PORTAL ','PERMISSION TO ACCESS PORTAL'),
	 ('ACCESS MOBILE APP','PERMISSION TO ACCESS MOBILE APP'),
	 ('CREATE USER','PERMISSION TO CREATE NEW USERS IN PORTAL');
