export const FILTER_INPUT_DEBOUNCE_MS = 2000;
export const FILTER_GROUP_VISIBLE_OPTIONS_STEP = 6;
export const FILTER_GROUP_SEARCH_MIN_OPTIONS = 6;

export const SESSION_COUNTDOWN_DURATION_MINUTES = 15;
export const SESSION_COUNTDOWN_RED_BELOW_MINUTES = 1;
export const SESSION_COUNTDOWN_PULSE_LAST_SECONDS = 15;
