apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: travelhub
  labels:
    project: travelhub
    environment: dev
spec:
  amiFamily: AL2023
  # Nombre del instance profile creado por Terraform: terraform output karpenter_node_instance_profile
  instanceProfile: "travelhub-dev-karpenter-node"
  amiSelectorTerms:
    - alias: al2023@latest
  subnetSelectorTerms:
    - tags:
        # Estas subnets son las privadas del VPC creado por Terraform
        kubernetes.io/role/internal-elb: "1"
  securityGroupSelectorTerms:
    - id: "REPLACE_WITH_EKS_NODE_SECURITY_GROUP_ID"
      # Obtener con: terraform output -raw eks_node_security_group_id
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 20Gi
        volumeType: gp3
        encrypted: true
  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 2
    httpTokens: required
  detailedMonitoring: false
