apiVersion: v1
kind: ServiceAccount
metadata:
  name: karpenter
  namespace: karpenter
  annotations:
<<<<<<< HEAD
    # ARN del IRSA role obtenido de Terraform
=======
>>>>>>> 4f8b825 (fixing terraform issues and karperter setup issues when recreating the infra)
    eks.amazonaws.com/role-arn: "arn:aws:iam::442042525047:role/travelhub-dev-karpenter-controller"
