image:
  repository: travelhub/booking-service

envVars:
  ENVIRONMENT: "production"
  INVENTORY_SERVICE_URL: "http://inventory-service:8000"
  IDENTITY_SERVICE_URL: "http://identity-service:8000"
  PAYMENT_SERVICE_URL: "http://payment-service:8000"
  PAYMENT_MOCK_ENABLED: "false"
  SEARCH_SERVICE_URL: "http://search-service:8000"
  BOOKING_EMAIL_ENABLED: "true"
  BOOKING_SMTP_HOST: "smtp.gmail.com"
  BOOKING_SMTP_PORT: "587"
  BOOKING_SMTP_STARTTLS: "true"
  BOOKING_SMTP_AUTH_ENABLED: "true"
  BOOKING_SMTP_USER: "travelhubnotifications@gmail.com"
  BOOKING_SMTP_FROM: "travelhubnotifications@gmail.com"

envFromSecrets:
  - envName: BOOKING_SMTP_APP_PASSWORD
    secretName: booking-service-smtp
    secretKey: BOOKING_SMTP_APP_PASSWORD
  - envName: DATABASE_URL
    secretName: booking-service-db
    secretKey: DATABASE_URL
  - envName: REDIS_URL
    secretName: booking-service-redis
    secretKey: REDIS_URL

envFromConfigMaps:
  - envName: SQS_BOOKING_EVENTS_URL
    configMapName: travelhub-config
    configMapKey: SQS_BOOKING_EVENTS_URL

