image:
  repository: travelhub/identity-service

hpa:
  maxReplicas: 8

envVars:
  ENVIRONMENT: "production"
  CORS_ORIGINS: "https://d3qrdjfvvzz7ms.cloudfront.net,http://localhost:5173"

envFromSecrets:
  - envName: DATABASE_URL
    secretName: identity-service-db
    secretKey: DATABASE_URL

