image:
  repository: travelhub/hotel-service

hpa:
  maxReplicas: 8

envVars:
  ENVIRONMENT: "production"

envFromSecrets:
  - envName: DATABASE_URL
    secretName: hotel-service-db
    secretKey: DATABASE_URL

