export const API_CONFIG = {
  IDENTITY_URL: process.env.EXPO_PUBLIC_IDENTITY_URL,
  SEARCH_URL: process.env.EXPO_PUBLIC_SEARCH_URL,
  ACCOMMODATION_URL: process.env.EXPO_PUBLIC_ACCOMMODATION_URL,
  BOOKING_URL: process.env.EXPO_PUBLIC_BOOKING_URL,
  WEB_APP_URL: process.env.EXPO_PUBLIC_WEB_APP_URL,
} as const;
